CFLAGS = -std=c99 -g -O0

PROGRAM = spectrev1_fence
SOURCE  = spectrev1_fence.c
     
all: $(PROGRAM)
     
$(PROGRAM): $(SOURCE) ; $(CC) $(CFLAGS) -o $(PROGRAM) $(SOURCE)
     
clean: ; rm -f $(PROGRAM)
